### ISSUE TITLE
Failing Cargo Audit, "Failure" Transitive dependency

### ISSUE THREAD

**Issue by smklein** [fussybeaver/bollard#101]
`cargo audit` fails for bollard because of a transitive dependency on `failure`, which is deprecated: https://github.com/RustSec/advisory-db/blob/master/crates/failure/RUSTSEC-2020-0036.toml

The transitive dependency comes from https://github.com/akshayknarayan/hyper-unix-connector - I've [made a PR](https://github.com/akshayknarayan/hyper-unix-connector/pull/1) to move the dependency to anyhow, but in the meantime, audit will be failing for bollard.

Posting this issue as a heads up.

**Comment by fussybeaver** [comment]
Thanks for investing time into this.
