### ISSUE TITLE
create_image not working with locally built image

### ISSUE THREAD

**Issue by rcastill** [fussybeaver/bollard#105]
If I locally build an image and name it "myimage" and try to use the API, it results in the following:
```rust
DockerResponseNotFoundError {
    message: "{\"message\":\"pull access denied for myimage, repository does not exist or may require \'docker login\': denied: requested access to the resource is denied\"}\n" 
}
```
I'm using the `CreateImageOptions { from_image: ... }` field.

I expect the result to be the same as if I call `create_image` on a pulled image. Am I missing something?

**Comment by fussybeaver** [comment]
I think the `CreateImage` API is specifically used to pull or import an image from an external registry. You can just use the image you built - e.g. the `CreateContainer` API, populating the `name` parameter with your newly built image.

**Comment by rcastill** [comment]
I get that, but if you are building something similar to `docker run` the steps should be: pull if need to pull; create container; start container.

How can I now if I meed to pull otherwise?

**Comment by fussybeaver** [comment]
not sure about the best way or how the CLI does it, but just off the top of my head you could try calling an `ImageHistory` https://docs.rs/bollard/0.8.0/bollard/struct.Docker.html#method.image_history, which IIRC will only work with an already pulled / built image. If you get a 404, you can catch it deal with it appropriately.

**Comment by rcastill** [comment]
Ok, I will try with that and follow up. Thanks!

**Comment by rcastill** [comment]
It worked nicely, thanks again!

Closing.
