### ISSUE TITLE
Logging driver outside Swagger OpenAPI specification

### ISSUE THREAD

**Issue by Rizary** [fussybeaver/bollard#110]
Apparently, I got this error:
```
 JsonDataError { message: "unknown variant `loki`, expected one of ``, `json-file`, `syslog`, `journald`, `gelf`, `fluentd`, `awslogs`, `splunk`, `etwlogs`, `none`
```
Because loki is not part of Docker OpenAPI spec. I'm not sure if it is maintained well, because as you can see [here](https://github.com/moby/moby/tree/master/daemon/logger), there is `gcplogs` that also not in OpenAPI spec.

So, what is the best option that I have right now?

**Comment by fussybeaver** [comment]
I suspect you're getting an enum variants that don't exist: we sometimes patch in additional values - https://github.com/fussybeaver/bollard/blob/d2f61648ec88009f37b61f405df5b48102acae29/codegen/src/main/java/bollard/BollardCodegen.java#L29-L59

Can you link exactly which enum / API endpoint you're having trouble with ?

**Comment by Rizary** [comment]
it's a https://github.com/grafana/loki. However, since https://github.com/moby/moby/issues/41246 arises, I am wondering how to make it work.

**Comment by zimbatm** [comment]
@fussybeaver it's this part of the API: https://github.com/moby/moby/blob/1a5b7f50bcc0da1ba6072e12f7ae7b73a3e5a89b/api/swagger.yaml#L867-L876

The issue is that the enum is not really an enum since plugins are able to extend the list of possible values.

**Comment by fussybeaver** [comment]
I guess we can just use a String instead of an Enum.
