### ISSUE TITLE
`Docker::events` not receiving events from Docker?

### ISSUE THREAD

**Issue by stepchowfun** [fussybeaver/bollard#113]
👋 I maintain a project called [Docuum](https://github.com/stepchowfun/docuum) which has been using Bollard since Docuum 1.12. The program listens for Docker events using Bollard's `Docker::events`.

During some testing tonight, I noticed that the Docuum no longer seems to actually receive any events from Docker (I can see events using the `docker events` command, but Bollard doesn't seem to pick them up), at least on my machine. From bisecting I have learned that Docuum 1.12+ does not receive Docker events, but previous versions work fine. That's the version when [we switched to Bollard](https://github.com/stepchowfun/docuum/pull/85).

The weird thing is: I remember this working. I bet @mdonoughe does too. I'm having a hard time believing Docuum hasn't been working since August (when we released 1.12). This makes me think a recent Docker upgrade may have caused the issue, and not a change in Bollard or Docuum.

Does Bollard have any automated integration testing for Docker events? If so, can we run them now with the latest version of Docker and see if they pass?

Bollard version: 0.8.0
Docker version: 19.03.13 (2.4.0.0), build 4484c46d9d
macOS 10.15.6 (19G2021)

**Comment by fussybeaver** [comment]
There does seem to be a problem with the events API on OSX, since it won't return a newline at the end of the payload like on linux, which we were using to delimit JSON events on a stream. I'm going to see if I can get the OSX executor working on circleci to have an integration test for this.

**Comment by fussybeaver** [comment]
I've merged it for now... the macos executor on circleci only works on a payment plan, so I'm going to look into github actions to see if that'll get me a macos integration test.
