### ISSUE TITLE
Any specific reason Docker::build_image implements stream instead of future?

### ISSUE THREAD

**Issue by TAK-YON** [fussybeaver/bollard#123]
pretty much title, i don't see why it needs to be a stream instead of a standard future.

**Comment by fussybeaver** [comment]
It was a standard future in the 0.8 release, but a recent bug confirmed that it needs to be a stream https://github.com/fussybeaver/bollard/pull/112

**Comment by TAK-YON** [comment]
gotcha, could you update the examples to reflect the changes since its misleading at the moment
