### ISSUE TITLE
How to use the Container::Config volumes field

### ISSUE THREAD

**Issue by TAK-YON** [fussybeaver/bollard#129]
Hey, having a bit of trouble understanding the usage of attaching a volume to a container

So with volumes it needs a HashMap<T, HashMap<(),()>. 
What i dont understand is what the key value pairs actually mean 

i'm guessing T is the path the volume will be mounted in the container but its the other hashmap that gets me. why a hashmap with a key and a value of ()? does the api only allow anonymous volumes?

**Comment by fussybeaver** [comment]
Yeah, it's a bit weird - the `volumes` field in `ContainerCreate` is only for anonymous volumes. If you want to simulate the `-v path/on/host:path/in/container` from the CLI, you need to use the `binds` field in the `HostConfig` configuration struct. If you want to mount to a pre-created volume, I believe you should use the `mounts` field in the `HostConfig` configuration struct. 

hth

**Comment by TAK-YON** [comment]
Right, thank you.
