### ISSUE TITLE
Release plan for support on tokio v0.3?

### ISSUE THREAD

**Issue by fanatid** [fussybeaver/bollard#130]
https://tokio.rs/blog/2020-10-tokio-0-3

**Comment by fussybeaver** [comment]
Currently blocked in bollard by https://github.com/tokio-rs/tokio/issues/3118

**Comment by chrisabruce** [comment]
I would appreciate v0.3 as well.

**Comment by jmjoy** [comment]
Should upgrade to tokio v1 now.

**Comment by fussybeaver** [comment]
Pending https://github.com/tokio-rs/tokio/pull/3388

**Comment by dfreese** [comment]
It kind of looks like the design discussion in https://github.com/tokio-rs/tokio/issues/3511 looks like it has stalled.

Given #140, would it be possible to release 0.10?

I haven't gotten too far in my search yet, but perhaps https://github.com/LucioFranco/tokio-compat-02 might help pull back in named pipe support in the meantime.

**Comment by fussybeaver** [comment]
Yep, I want to publish a new `bollard-stubs` version, since the upstream API got bumped to 1.41 and should be good to go.
