### ISSUE TITLE
New MemoryStatsStats enum prevents json deserialization

### ISSUE THREAD

**Issue by aserowy** [fussybeaver/bollard#152]
Hi,

we've got problems with this change. We are running api 1.41.

![image](https://user-images.githubusercontent.com/8199164/116802711-52fe6a00-ab15-11eb-890b-9f15961d4dfd.png)

While everything works fine, we got errors streaming stats with the new variants.

![image](https://user-images.githubusercontent.com/8199164/116802744-8ccf7080-ab15-11eb-92ab-5d7212c370a1.png)

The json result from stream looks exactly like [ContainerStats](https://docs.docker.com/engine/api/v1.41/#operation/ContainerStats), which does not know about c groups.

```json
{
  "read": "2021-05-02T05:10:29.5953243Z",
  "preread": "2021-05-02T05:10:28.5614296Z",
  "pids_stats": { "current": 18 },
  "blkio_stats": {
    "io_service_bytes_recursive": [],
    "io_serviced_recursive": [],
    "io_queue_recursive": [],
    "io_service_time_recursive": [],
    "io_wait_time_recursive": [],
    "io_merged_recursive": [],
    "io_time_recursive": [],
    "sectors_recursive": []
  },
  "num_procs": 0,
  "storage_stats": {},
  "cpu_stats": {
    "cpu_usage": {
      "total_usage": 193674787300,
      "percpu_usage": [
        38839858700,
        7732528900,
        40562396900,
        9015874200,
        38276766600,
        11291387200,
        38560103400,
        9395871400
      ],
      "usage_in_kernelmode": 26410000000,
      "usage_in_usermode": 78130000000
    },
    "system_cpu_usage": 4438290140000000,
    "online_cpus": 8,
    "throttling_data": {
      "periods": 0,
      "throttled_periods": 0,
      "throttled_time": 0
    }
  },
  "precpu_stats": {
    "cpu_usage": {
      "total_usage": 193673934900,
      "percpu_usage": [
        38839686400,
        7732409700,
        40562396900,
        9015874200,
        38276205700,
        11291387200,
        38560103400,
        9395871400
      ],
      "usage_in_kernelmode": 26410000000,
      "usage_in_usermode": 78130000000
    },
    "system_cpu_usage": 4438281850000000,
    "online_cpus": 8,
    "throttling_data": {
      "periods": 0,
      "throttled_periods": 0,
      "throttled_time": 0
    }
  },
  "memory_stats": {
    "usage": 196747264,
    "max_usage": 199966720,
    "stats": {
      "active_anon": 89210880,
      "active_file": 946176,
      "cache": 4653056,
      "dirty": 405504,
      "hierarchical_memory_limit": 9223372036854771712,
      "hierarchical_memsw_limit": 9223372036854771712,
      "inactive_anon": 92180480,
      "inactive_file": 3108864,
      "mapped_file": 135168,
      "pgfault": 366630,
      "pgmajfault": 66,
      "pgpgin": 205755,
      "pgpgout": 185872,
      "rss": 180195328,
      "rss_huge": 100663296,
      "total_active_anon": 89210880,
      "total_active_file": 946176,
      "total_cache": 4653056,
      "total_dirty": 405504,
      "total_inactive_anon": 92180480,
      "total_inactive_file": 3108864,
      "total_mapped_file": 135168,
      "total_pgfault": 366630,
      "total_pgmajfault": 66,
      "total_pgpgin": 205755,
      "total_pgpgout": 185872,
      "total_rss": 180195328,
      "total_rss_huge": 100663296,
      "total_unevictable": 0,
      "total_writeback": 0,
      "unevictable": 0,
      "writeback": 0
    },
    "limit": 13355659264
  },
  "name": "/home-assistant",
  "id": "2a7054d569ebeb767d6d4eead95833a765c5fa3c443330fdb94366bd7c0cc913",
  "networks": {
    "eth0": {
      "rx_bytes": 739081,
      "rx_packets": 6900,
      "rx_errors": 0,
      "rx_dropped": 0,
      "tx_bytes": 2196039,
      "tx_packets": 21172,
      "tx_errors": 0,
      "tx_dropped": 0
    }
  }
}
```

Am i missing something? If you need further information or investigation, just give me a ping :)

Kind regards
Alexander

_Originally posted by @aserowy in https://github.com/fussybeaver/bollard/issues/143#issuecomment-830742638_

**Comment by aserowy** [comment]
Hi,

sry for double posting, but i could not reopen the issue.

Kind regards
Alexander

**Comment by fussybeaver** [comment]
I think the master branch has some changes to that, fixed in https://github.com/fussybeaver/bollard/pull/144 which are not published yet in the crate.

**Comment by aserowy** [comment]
We are running v10.1 currently: https://github.com/aserowy/docker2mqtt/blob/10-stream-logging/Cargo.toml

**Comment by fussybeaver** [comment]
No, you'll need to use a git dependency https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories until I release a new version.

**Comment by aserowy** [comment]
Do you have an eta for release? :D Or can we help you to speed up the process?

**Comment by fussybeaver** [comment]
Hmm.. you're right that PR should be in the release. Maybe it's a bug that needs fixing..

**Comment by aserowy** [comment]
Ok tomorrow ill look into it, and give you feedback.

**Comment by aserowy** [comment]
![image](https://user-images.githubusercontent.com/8199164/116809477-7e497f00-ab3e-11eb-8bba-e5f44bf4eee2.png)

**Comment by fussybeaver** [comment]
Thanks for taking a look into it

**Comment by aserowy** [comment]
Ok, first findings: I played with the code in playground and there is no failure. I resettet my env to main and it worked out of the box with 0.10.0 after upgrading dependencies (but leaving bollard on 0.10.0) the exception gets thrown.
Next step is to look into the dependencies.
Thus, the issue can be closed here :)

**Comment by fussybeaver** [comment]
OK.. yeah, the Cargo lockfile can be funny sometimes.

**Comment by aserowy** [comment]
Found it... :D

we've used BunjanFormattingLayer for our logs, which adds arbitrary_precision to all deserializations... found it here https://github.com/serde-rs/json/issues/559

(leaving it hear, if someone else stumbles across it)
