### ISSUE TITLE
DockerResponseServerError 500: pulling docker images

### ISSUE THREAD

**Issue by mlilien** [fussybeaver/bollard#155]
Hi,

I use an image from an azure container registry, which i can pull localy via `docker pull`.
In my application using bollard, I get a DockerResponseServerError 500 though.

```
DockerResponseServerError {
    status_code: 500,
    message: "{\"message\":\"Head https://xxx.azurecr.io/v2/xxx/xxx/manifests/latest: unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information.\"}\n",
})
Error: Kind(Other)
``` 
my `~/.docker/config.json`:
```
{
	"auths": {
		"xxx.azurecr.io": {
			"auth": "xxx==",
			"identitytoken": "xxx"
		}
	}
}
```
My dev environment is windows wsl2 with docker for windows.
Does bollard use this docker configuration file, or am I supposed to parse it and provide it via `AuthConfig`?

**Comment by fussybeaver** [comment]
Yes, you need to provide authentication using the [`DockerCredentials`](https://docs.rs/bollard/0.10.1/bollard/auth/struct.DockerCredentials.html) configuration. You can find an example in [the events integration test](https://github.com/fussybeaver/bollard/blob/f458fed68c4af4d55c1256189308bfde79c75263/tests/system_test.rs#L34-L49).

**Comment by mlilien** [comment]
Thank you!

**Comment by stuhood** [comment]
Hey folks: I found this ticket while searching for recommendations around authentication. Since this was closed, it looks like the https://crates.io/crates/docker_credential crate has been published.

It's possible that `bollard` could reference that crate, or perhaps integrate it behind a feature? Let me know if a patch might be accepted for that.

**Comment by fussybeaver** [comment]
Yes, I think it should be a good enhancement if it's feature-flagged.
