### ISSUE TITLE
Using podman to create image

### ISSUE THREAD

**Issue by dwhiteddsoft** [fussybeaver/bollard#160]
Under the covers I am simply using the podman sock as they are API compliant but am running into a little problem. If I use the following code:
```rust
    async fn create_image(container: ContainerManifest, settings: &Settings) -> Result<(), Error> {
       let docker = match Self::connect().await
       {
           Ok(d) => d,
           Err(e) => return Err(e),
       };
       println!("create_image <--");
       //create image
       let img_info = docker
            .create_image(
                Some(CreateImageOptions {
                    from_image: &container.image_ref[..],
                    ..Default::default()
                }),
                None,
                Some(Self::integration_test_registry_credentials(settings)),
            )
            .try_collect::<Vec<_>>()
            .await?;
        println!("returned: {:?}",img_info);
        println!("create_image -->");
        Ok(())
    }
```
I get the following error and am a bit flummoxed. 
returned: [CreateImageInfo { id: None, error: Some("write /dev/stderr: input/output error\n"), status: None, progress: None, progress_detail: Some(ProgressDetail { current: None, total: None }) }]

I can do a CLI 'pull' and as long as the image is there, starts, stops, etc work fine. Any help appreciated

**Comment by fussybeaver** [comment]
Can you try setting up the `env_logger` crate with the `RUST_LOG=bollard=debug` environment variable, check the URL being posted in your request. You can try to reproduce with `curl`. It might be a particular parameter that is unsupported.

Also which version of podman, and does it have any logs ?

**Comment by dwhiteddsoft** [comment]
It is API compliant. It seems I was having a system level problem with podman. Thanks for the support. I hope to pay it back.
