### ISSUE TITLE
JSON decode error when reading `import_image()` stream

### ISSUE THREAD

**Issue by indygreg** [fussybeaver/bollard#171]
Thank you for writing this crate!

I'm calling the `import_image()` function to hit the `/images/load` endpoint to upload an uncompressed tar file into Docker. It seems to always work locally. However, on GitHub Actions, it intermittently encounters an error due to a JSON parse failure.

```rust
    let tar_data = b"...";
    let options = ImportImageOptions::default();

    let mut stream = docker.import_image(options, Body::from(tar_data), None);

    while let Some(info) = stream.try_next().await? {
        ...
    }
```

This will intermittently hit a `bollard::Error::JsonSerdeError` where the serde error will be something like `Error(\"EOF while parsing an object\", line: 1, column: 83)"`.

I'm not sure if Docker is sending malformed JSON or if this crate's stream parsing code isn't resilient to some buffering scenarios where the JSON payload is split (or something). I'm connected to the Docker UNIX domain socket.

I was hoping I'd be able to selectively ignore the `bollard::Error::JsonSerdeError` variant and continue processing the remainder of the server response. However, it appears that the full response stream is in an error state as soon as this error occurs, effectively aborting the entire Docker operation.

This error is annoying, but can be worked around easily enough by retrying. But I figured I'd file the issue for visibility in case others see it.

**Comment by fussybeaver** [comment]
Thanks for the report. What machine executor (linux/OSX) are you using on GitHub Actions and locally ?

**Comment by indygreg** [comment]
In GitHub Actions, Ubuntu 20.04, which according to https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#tools is Docker 20.10.10.

Locally, Ubuntu 21.10 with Docker 20.10.10.

**Comment by fussybeaver** [comment]
I had some trouble trying to reproduce this, but I did finally manage to reliably trigger this error on your project: https://github.com/fussybeaver/portable-clang/runs/4310424652?check_suite_focus=true 

I wasn't able to debug this further on that project, I'm not entirely sure why this only happens on one particular build and not others - perhaps an arbitrary configuration in the docker daemon that's toggled through a GitHub experiment that's not the default ?

At any rate, I managed to reproduce this with a unit test, so I've created a PR that'll hopefully fix this.

**Comment by indygreg** [comment]
That's so weird you could only trigger this on my project! I have no clue why that may be: I don't think I'm doing anything funky with Docker or GitHub Actions in my project. Who knows.

Thanks for the investigation and for fixing this bug!
