### ISSUE TITLE
Target field of ListContainers mounts is always None

### ISSUE THREAD

**Issue by thechubbypanda** [fussybeaver/bollard#191]
Summary of the issue: `ListContainers > ContainerSummaryInner > Mounts > Mount > Target == None` for all containers despite `docker container inspect` showing the data exists.

Mounts for a container:
```
Some([Mount { target: None, source: Some("/var/run/docker.sock"), typ: Some(BIND), read_only: None, consistency: None, bind_options: None, volume_options: None, tmpfs_options: None }, Mount { target: None, source: Some("/var/lib/docker/volumes/portainer_data/_data"), typ: Some(VOLUME), read_only: None, consistency: None, bind_options: None, volume_options: None, tmpfs_options: None }])
```

Target for `/var/run/docker.sock` should be `/var/run/docker.sock`  
Target for `/var/lib/docker/volumes/portainer_data/_data` should be `/data`

**Comment by fussybeaver** [comment]
Thanks for the report. Do you think this is related to portainer, or is it reproducible on a plain docker?

**Comment by thechubbypanda** [comment]
I'm running a pure docker environment, no portainer.

**Comment by thechubbypanda** [comment]
I believe I've found a potential cause of the error.

Looking at the response content for a list_containers:

>"Mounts":[{"Type":"volume","Name":"portainer_data","Source":"/var/lib/docker/volumes/portainer_data/_data","Destination":"/data","Driver":"local","Mode":"z","RW":true,"Propagation":""},{"Type":"bind","Source":"/var/run/docker.sock","Destination":"/var/run/docker.sock","Mode":"","RW":true,"Propagation":"rprivate"}]

It appears that the `Target` is actually called `Destination`.

Could this be the issue?

**Comment by thechubbypanda** [comment]
Still looking through the code, there appears to be 2 mount types: `Mount` and `MountPoint`

`MountPoint` is used by `ContainerInspectResponse` wheras `Mount` is used by `ContainerInnerSummary`

`MountPoint` appears to work correctly (in terms of Target value) but `Mount` does not.

`MountPoint::target` has a serde serialization as `Destination`. 
Not sure if the fix for `Mount` is as simple as that but if someone has a chance to fix this, hopefully this diagnosis helps.

**Comment by thechubbypanda** [comment]
I believe that I've found the issue and it's not the fault of Bollard.

I've created an [issue](https://github.com/docker/for-linux/issues/1361) regarding the docker API mismatch between `Target` and `Destination` for the endpoint `/containers/json`.

**Comment by fussybeaver** [comment]
Thanks for raising a ticket upstream. I'll update the models when the swagger spec is updated.
