### ISSUE TITLE
Implement PartialEq for structs to facilitate mocking

### ISSUE THREAD

**Issue by giggio** [fussybeaver/bollard#209]
I'm trying to mock the calls to bollard (using `mockall`), but the lack of impl for `PartialEq` for some structs does not allow to properly create the expectations.

For example, I can't do this:

```rust
let mut hasContainersMock = MockHasContainers::new();
let mut filter = HashMap::new();
filter.insert("status", vec!["running"]);
hasContainersMock
    .expect_list_containers()
    .with(eq(Some(ListContainersOptions {
        all: true,
        filters: filter,
        ..Default::default()
    })))
```

It fails, because `ListContainersOptions` does not implement `PartialEq`.

**Comment by fussybeaver** [comment]
Is this generally for all the endpoint parameter option structs? Feel free to prepare a PR adding `PartialEq` to what you need
