### ISSUE TITLE
NewlineLogOutputDecoder doesn't always correctly split

### ISSUE THREAD

**Issue by uellenberg** [fussybeaver/bollard#229]
Hello, I've noticed that the stdout stream from Docker::exec seems to have some trouble splitting on large amounts of data. I'm currently using stdin/stdout as a communication channel between my container and host (sending base64 encoded messages back-and-forth), as the container has no other means of communication (no network and such), and I've found that I have to wrap each line of output in `BufRead::lines(Cursor::new(line.to_string()))` to correctly split everything (though this isn't the biggest issue). My main issue is that if I send relatively large amounts of text (~100kb), the lines given to me seem to be cut off, which causes issues as my messages become cut in half. Is there any way I can solve this?

**Comment by fussybeaver** [comment]
Thanks for the report. It'd be useful to have a reliable test case, or an example to build on.

**Comment by uellenberg** [comment]
> Thanks for the report. It'd be useful to have a reliable test case, or an example to build on.

Here's a quick example I put together using the Ubuntu image (though any image should work):
```rust
use bollard::Docker;
use bollard::exec::{CreateExecOptions, StartExecResults};
use futures_util::stream::StreamExt;

#[tokio::main]
async fn main() {
    let docker = Docker::connect_with_socket_defaults().unwrap();
    let res = docker.create_exec("b4106240713c", CreateExecOptions {
        cmd: Some(vec!["/bin/bash", "-c", "printf '=%.0s' {1..1000000}"]),
        attach_stdout: Some(true),
        attach_stdin: Some(true),
        attach_stderr: Some(false),
        tty: Some(true),
        ..Default::default()
    }).await.unwrap();

    match docker.start_exec(&*res.id, None).await {
        Ok(StartExecResults::Attached { output, input }) => {
            output.for_each(|line| async {
                println!("{}", line.unwrap().to_string().len());
            }).await;
        }
        _ => {}
    }
}
```

The line is capped to 1024 characters, which fine for logging but far too little for anything else.
