### ISSUE TITLE
stop using chrono

### ISSUE THREAD

**Issue by lizelive** [fussybeaver/bollard#231]
https://rustsec.org/advisories/RUSTSEC-2020-0159

**Comment by lizelive** [comment]
https://github.com/fussybeaver/bollard/pull/188

**Comment by fussybeaver** [comment]
There is a PR solving this security issue in chronos.. https://github.com/chronotope/chrono/pull/677

Still hopeful that this will fix it. Happy to hear what the general consensus is about this though.

**Comment by fussybeaver** [comment]
I've now merged #188 - chrono is an optional dependency in release v0.13.0
