### ISSUE TITLE
Is there any way to pull an image?

### ISSUE THREAD

**Issue by flaxeneel2** [fussybeaver/bollard#233]
Hi,
I am trying to programmatically pull an image, i want to basically do the same thing that docker does when you run `docker image pull <image>` but for some reason, no matter what i try, it does not work. Is this supported by bollard?

**Comment by fussybeaver** [comment]
Yes, you can take a look at some of the examples, e.g. https://github.com/fussybeaver/bollard/blob/master/examples/exec.rs - runs through pulling and running a container and attaching to the output stream. Pulling in the API is essentially [`create_image`](https://docs.rs/bollard/latest/bollard/struct.Docker.html#method.create_image).

**Comment by flaxeneel2** [comment]
Ah, I see. Thank you, also before closing this I wanted to ask, is it not possible to specify limits on container creation? the only way i see is having to update the container just after creation to set these limits.

**Comment by flaxeneel2** [comment]
Nevermind I figured oyt I can just provide a host config in my config when making the container, thanks
