### ISSUE TITLE
Allow support for custom headers?

### ISSUE THREAD

**Issue by alakhpc** [fussybeaver/bollard#243]
Would it be possible to add custom headers in `connect_with_http`?, This would allow remote connections where authentication is needed

**Comment by fussybeaver** [comment]
At the moment, additional credentials used for example as part of registry authentication are part of the call method parameters, e.g. the `create_image` method. https://github.com/fussybeaver/bollard/blob/e1046a48499eb2068790b2679b2e068ea03f1920/src/image.rs#L527
