### ISSUE TITLE
Bollard leaks conmon processes when executing processes with a podman backend

### ISSUE THREAD

**Issue by MarkRx** [fussybeaver/bollard#246]
When using bollard to execute processes using a podman backend conmon processes are leaked. As far as I can tell there is no cleanup needed after using create/start exec. Normal podman exec commands do not leak conmon processes.

Environment:
bollard: 0.13.0
os: RHEL 8.6
podman: 4.0.2

Steps to reproduce:
1. Install & configure podman for running images in rootless mode
2. Install the docker-podman alias package and set DOCKER_HOST to the podman unix socket
3. Launch any image 

> docker run --rm -ti registry.access.redhat.com/ubi8/ubi:latest /bin/bash

4. Obtain the container id with `docker ps`
5. Setup a watch on processes for the user running podman:

> watch ps -ux -U myuser

6. Run the below program with the container id as the first parameter

> ./bollard_conmon e50b946b3bbe

7. Observe in the ps watch that conmon processes are launched when the sleep command is run but do not terminate until the image is killed

> myuser   28551  0.0  0.0 143860  2452 ?        Ssl  14:18   0:00 /usr/bin/conmon --api-version 1 -c e50b946b3bbee1cc1398d75d09a555bab6
> myuser   28583  0.0  0.0 143860   828 ?        S    14:18   0:00 /usr/bin/conmon --api-version 1 -c e50b946b3bbee1cc1398d75d09a555bab6
> myuser   28586  0.0  0.0 143860  2420 ?        Ssl  14:18   0:00 /usr/bin/conmon --api-version 1 -c e50b946b3bbee1cc1398d75d09a555bab6
> myuser   28617  0.0  0.0 143860   828 ?        S    14:18   0:00 /usr/bin/conmon --api-version 1 -c e50b946b3bbee1cc1398d75d09a555bab6
> myuser   28622  0.0  0.0 143860  2484 ?        Ssl  14:18   0:00 /usr/bin/conmon --api-version 1 -c e50b946b3bbee1cc1398d75d09a555bab6
> myuser   28658  0.0  0.0 143860   832 ?        S    14:18   0:00 /usr/bin/conmon --api-version 1 -c e50b946b3bbee1cc1398d75d09a555bab6
> myuser   28660  0.0  0.0 143860  2336 ?        Ssl  14:18   0:00 /usr/bin/conmon --api-version 1 -c e50b946b3bbee1cc1398d75d09a555bab6
> myuser   28692  0.0  0.0 143860   828 ?        S    14:18   0:00 /usr/bin/conmon --api-version 1 -c e50b946b3bbee1cc1398d75d09a555bab6

The full process info looks like this:

> myuser   32868  0.0  0.0 143860  2292 ?        Ssl  14:29   0:00 /usr/bin/conmon --api-version 1 -c 6d089503ca57fdafda0398714e706060c04bd2d4ca5c19979040cd27fc5fa75d -u 5fb252cc1cc658611c3c332358fd08e476d649e235ca1cada65d3cfb0a2753cd -r /usr/bin/runc -b /var/appl/jenkins/home/myuser/.local/share/containers/storage/overlay-containers/6d089503ca57fdafda0398714e706060c04bd2d4ca5c19979040cd27fc5fa75d/userdata/5fb252cc1cc658611c3c332358fd08e476d649e235ca1cada65d3cfb0a2753cd -p /var/appl/jenkins/home/myuser/.local/share/containers/storage/overlay-containers/6d089503ca57fdafda0398714e706060c04bd2d4ca5c19979040cd27fc5fa75d/userdata/5fb252cc1cc658611c3c332358fd08e476d649e235ca1cada65d3cfb0a2753cd/exec_pid -n dreamy_feistel --exit-dir /var/appl/jenkins/home/myuser   /.local/share/containers/storage/overlay-containers/6d089503ca57fdafda0398714e706060c04bd2d4ca5c19979040cd27fc5fa75d/userdata/5fb252cc1cc658611c3c332358fd08e476d649e235ca1cada65d3cfb0a2753cd/exit --full-attach -l none --log-level info --runtime-arg --log-format=json --runtime-arg --log --runtime-arg=/var/appl/jenkins/home/myuser/.local/share/containers/storage/overlay-containers/6d089503ca57fdafda0398714e706060c04bd2d4ca5c19979040cd27fc5fa75d/userdata/5fb252cc1cc658611c3c332358fd08e476d649e235ca1cada65d3cfb0a2753cd/oci-log -e --exec-attach --exec-process-spec /var/appl/jenkins/home/myuser/.local/share/containers/storage/overlay-containers/6d089503ca57fdafda0398714e706060c04bd2d4ca5c19979040cd27fc5fa75d/userdata/5fb252cc1cc658611c3c332358fd08e476d649e235ca1cada65d3cfb0a2753cd/exec-process-3112598379 --exit-command /usr/bin/podman --exit-command-arg --root --exit-command-arg /var/appl/jenkins/home/myuser/.local/share/containers/storage --exit-command-arg --runroot --exit-command-arg /run/user/78572/containers --exit-command-arg --log-level --exit-command-arg info --exit-command-arg --cgroup-manager --exit-command-arg cgroupfs --exit-command-arg --tmpdir --exit-command-arg /run/user/78572/libpod/tmp --exit-command-arg --network-config-dir --exit-command-arg  --exit-command-arg --network-backend --exit-command-arg cni --exit-command-arg --runtime --exit-command-arg runc --exit-command-arg --storage-driver --exit-command-arg overlay --exit-command-arg --events-backend --exit-command-arg file --exit-command-arg container --exit-command-arg cleanup --exit-command-arg --rm --exit-command-arg --exec --exit-command-arg 5fb252cc1cc658611c3c332358fd08e476d649e235ca1cada65d3cfb0a2753cd --exit-command-arg 6d089503ca57fdafda0398714e706060c04bd2d4ca5c19979040cd27fc5fa75d --exit-delay 300

src/main.rs:
```rust
use std::env;

use bollard::{exec::{StartExecResults, CreateExecOptions}, container::LogOutput, Docker, errors::Error};
use futures::StreamExt;

/// Executes a command in a container and returns (stdout, stderr)
async fn exec_container(docker: &Docker, container_id: &str, cmd: &[&str]) -> Result<(String, String), Error> {
    let mut stdout = String::with_capacity(1024);
    let mut stderr = String::with_capacity(1024);

    let container_id_str = &container_id[0..7];

    println!("Exec [{}]: {}", container_id_str, cmd.join(" "));
    let config = CreateExecOptions {
        cmd: Some(cmd.to_vec()),
        attach_stdout: Some(true),
        attach_stderr: Some(true),
        ..Default::default()
    };

    let exec = docker.create_exec(&container_id, config).await?.id;

    if let StartExecResults::Attached { mut output, .. } = docker.start_exec(&exec, None).await? {
        while let Some(Ok(msg)) = output.next().await {
            match msg {
                LogOutput::StdErr { message } => {
                    let str = String::from_utf8_lossy(&message);
                    println!("stderr [{}]: {}", container_id_str, str);
                    stderr.push_str(&str);
                }
                LogOutput::StdOut { message } => {
                    let str = String::from_utf8_lossy(&message);
                    println!("stdout [{}]: {}", container_id_str, str);
                    stdout.push_str(&str);

                },
                _default => {  }
            }
        }
    } else {
        unreachable!();
    }

    return Ok((stdout, stderr));
}

#[tokio::main]
async fn main() {
    let args: Vec<String> = env::args().collect();

    // Set DOCKER_HOST env variable to the podman socket. Example: DOCKER_HOST=unix:///run/user/78572/podman/podman.sock
    let docker = Docker::connect_with_unix_defaults().unwrap();
    let container_id = &args[1];

    loop {
        let cmd = vec!["/usr/bin/sleep", "5"];

        let _ = exec_container(&docker, container_id, &cmd).await.unwrap();
    }
}
```

Cargo.toml:
```
[package]
name = "bollard_conmon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bollard = "0.13.0"
futures = "0.3.21"
tokio = { version = "1.19.2", features = ["macros", "process", "rt-multi-thread", "sync"] }
```

**Comment by MarkRx** [comment]
This also happens when using a Rust podman library (granted the APIs should be compatible). I'm investigating if the problem might be with podman itself...

https://github.com/vv9k/podman-api-rs/issues/130

**Comment by fussybeaver** [comment]
Thanks for reporting... I think the conmon process is part of the podman stack, so I'm guessing this is probably related to podman, though I'll try and reproduce this on my local machine (I don't have RHEL installed, so it'll just be plain docker).

**Comment by MarkRx** [comment]
Closing as this is an issue with podman itself and not the bollard library - https://github.com/containers/podman/issues/15377
