### ISSUE TITLE
add platform parameter to create_container

### ISSUE THREAD

**Issue by tdyas** [fussybeaver/bollard#258]
The Moby client seems to support a `platform` parameter sent as a query parameter for the create container API. See https://github.com/moby/moby/blob/924edb948c2731df3b77697a8fcc85da3f6eef57/client/container_create.go#L46-L49. 

Are there plans to add this to `bollard`?

**Comment by fussybeaver** [comment]
Happy to accept a PR

**Comment by tdyas** [comment]
https://github.com/fussybeaver/bollard/pull/259
