### ISSUE TITLE
Is secret API implementaion missing?

### ISSUE THREAD

**Issue by zozzz** [fussybeaver/bollard#260]
This API implementation is missing or i'am dumb to finding it? https://docs.docker.com/engine/api/v1.41/#tag/Secret

**Comment by fussybeaver** [comment]
Some of the swarm API endpoints are not implemented, though the API models for these endpoints [should be generated]( https://github.com/fussybeaver/bollard/blob/9f150efd94b350a8dfed1ad563ce93c8f116a641/codegen/target/generated-sources/src/models.rs#L4471-L4524 ), so it's not a lot of work to create a PR.

Is it just the secrets endpoints that you need?

**Comment by zozzz** [comment]
Currently i think yes, only this endpoint is needed. I create a PR for this when i ready.

**Comment by zozzz** [comment]
The `SecretSpec.data` requires _Base64-url-safe-encoded_ value. What do you think do i implement this special case in codegen or just simply write example that use base64 encoded value?

**Comment by fussybeaver** [comment]
I would leave it to the user to base64 encode and just receive the payload as a struct argument to the method and pass it onto the endpoint (so write example with base64 encoded value).
