### ISSUE TITLE
Missing `name` option in container creation config

### ISSUE THREAD

**Issue by ClementNerma** [fussybeaver/bollard#268]
Hi!

I found out that `bollard::container::Config`, the struct used to create Docker containers, was missing the `name` option to name a container.

Could it be possible to add it or was it intentionnally left out?

**Comment by chanble** [comment]
It contained the first argument[CreateContainerOptions](https://docs.rs/bollard/latest/bollard/container/struct.CreateContainerOptions.html#) .   [the create_container doc ](https://docs.rs/bollard/latest/bollard/struct.Docker.html#method.create_container)

**Comment by ClementNerma** [comment]
Oh my bad, I even used it myself 🤦 
Sorry for the inconvenience.
