### ISSUE TITLE
Missing 'pull' option in `Docker::create_container`

### ISSUE THREAD

**Issue by ClementNerma** [fussybeaver/bollard#271]
Hi!

It seems like the `pull` option is missing from the `Docker::create_container` method.

As per Docker's documentation, this option can either be `always`, `missing` or `never`.

**EDIT:** I checked [Docker's API reference](https://docs.docker.com/engine/api/v1.41/#tag/Container/operation/ContainerCreate) and it seems like the `pull` option only exists in the CLI, which is really weird.

I guess that means you need to create an image in order to create a container (if you don't execute it immediately)? This is weird.

**Comment by fussybeaver** [comment]
Yes, the docker CLI does a few extra things. To pull an image you use `create_image`.

**Comment by ClementNerma** [comment]
I've tried that I keep getting the following error:

```
Docker responded with status code 400: invalid reference format: repository name must be lowercase
```

When the image is just `crccheck/hello-world` (I've also tried with `crccheck/hello-world:latest`)

**Comment by ClementNerma** [comment]
Ok so I'm plain stupid, the exact code I was using was reading the image name from a variable, and I used the one containing the container's name instead of its image 🤦 

Sorry for the inconvenience.
