### ISSUE TITLE
[ BUG ] - timestamp line parsing

### ISSUE THREAD

**Issue by mrjackwills** [fussybeaver/bollard#285]
I am using your library extensively in my own application, [oxker](https://www.github.com/mrjackwills/oxker), but I can't work out whether an issue that has appeared lies with my own code, my configuration of bollard, or if I have a found a unique edge-case.

When I am trying to read the logs, a very specific log line is causing the log line to be split incorrectly.
The line, taken directly from `docker logs -t my_container`, is 
`2023-01-14T23:17:27.496421984-05:00 [lighttpd] 2023/01/14 23:17:27 2023-01-14 23:17:26: server.c.1513) server started (lighttpd/1.4.59)`

But, in my application (and the example application below), this is being split into
`2023-01-14T23:17:27.496421984-05:00 [lighttpd] 2023/01/14 23`, and, 
`:17:27 2023-01-14 23:17:26: server.c.1513) server started (lighttpd/1.4.59)\r\n`.

Due to, the somewhat complexity, of [oxker](https://www.github.com/mrjackwills/oxker), I have made a simple example, and the problem still persists.
**Cargo.toml**
```toml
[package]
name = "docker_test"
version = "0.1.0"
edition = "2021"

[dependencies]
bollard = "0.13.0"
futures-util = "0.3.25"
tokio = {version = "1.24", features=["full"]}
```

**main.rs**
```rust
use bollard::{
    container::{ListContainersOptions, LogsOptions},
    Docker,
};
use futures_util::StreamExt;

#[tokio::main]
async fn main() {
    if let Ok(docker) = Docker::connect_with_socket_defaults() {
        if docker.ping().await.is_ok() {
            get_ids(&docker).await;
        }
    }
}

async fn get_ids(docker: &Docker) {
    let containers = docker
        .list_containers(Some(ListContainersOptions::<String> {
            all: true,
            ..Default::default()
        }))
        .await
        .unwrap_or_default();

    for i in containers {
        update_log(docker, i.id.unwrap().as_str()).await;
    }
}

async fn update_log(docker: &Docker, id: &str) {
    let options = Some(LogsOptions::<String> {
        stdout: true,
        timestamps: true,
        ..Default::default()
    });
    let mut logs = docker.logs(id, options);

    while let Some(Ok(value)) = logs.next().await {
        let data = value.to_string();
        if !data.trim().is_empty() {
            println!("{:?}", data);
        }
    }
}
```
At the moment, I am using this, probably inefficient and verbose, function, to check for this unique edge-case
```rust
    fn line_starts_timestamp(val: &str) -> bool {
        if val.len() < 29 {
            return false;
        };
        let c = || val.chars();
        [
            c().take(4).all(|c| c.is_ascii_digit()),
            c().skip(4).take(1).all(|c| c == '-'),
            c().skip(5).take(2).all(|c| c.is_ascii_digit()),
            c().skip(7).take(1).all(|c| c == '-'),
            c().skip(8).take(2).all(|c| c.is_ascii_digit()),
            c().skip(10).take(1).all(|c| c == 'T'),
            c().skip(11).take(2).all(|c| c.is_ascii_digit()),
            c().skip(13).take(1).all(|c| c == ':'),
            c().skip(14).take(2).all(|c| c.is_ascii_digit()),
            c().skip(16).take(1).all(|c| c == ':'),
            c().skip(17).take(2).all(|c| c.is_ascii_digit()),
            c().skip(19).take(1).all(|c| c == '.'),
            c().skip(20).take(9).all(|c| c.is_ascii_digit()),
        ]
        .into_iter()
        .all(|f| f)
    }
```
Am I missing something obvious?

**Comment by fussybeaver** [comment]
Hmm... That's a little odd, because Docker's log output sends a length in the header of each line that it outputs, which is what Bollard uses to split lines.

You could probably glean more information by adding the `env_logger` dependency and setting the environment `RUST_LOG=bollard=debug`. This should give an indication whether Bollard's line encoder is prematurely splitting the line.

Also might be worth `curl`-ing the docker socket log endpoint to see what the raw data looks like.

My attempts to reproduce it so far are not succeeding - I ran a lighttpd container but the lines are splitting correctly. What architecture is your docker server running on?

**Comment by mrjackwills** [comment]
Thanks, I'll see what comes up with the env logger, and curling direct.

This specific issue is occurring, at least on my testing so far, on a aarch64 machine, specifically an pi4, the container in question is [this one](https://github.com/sdr-enthusiasts/docker-readsb-protobuf/pkgs/container/docker-readsb-protobuf), although not sure if it'll work without the whole setup - it's part of a docker compose network for receiving/decoding adsbdb data, via a usb adapter & aerial, and submitting to various websites.

**Comment by mrjackwills** [comment]
Using the `RUST_LOG=bollard=debug` and `env_logger` crate, I get the following output
```
[2023-01-15T17:11:59Z DEBUG bollard::read] NewlineLogOutputDecoder: not enough data for read header
[2023-01-15T17:11:59Z DEBUG bollard::read] NewlineLogOutputDecoder: no header found, return LogOutput::Console
"2023-01-14T23:17:26.551706337-05:00 [readsb] 2023/01/14 23:17:26 rtlsdr: tuner gain set to 38.6 dB\r\n"
[2023-01-15T17:11:59Z DEBUG bollard::read] NewlineLogOutputDecoder: not enough data for read header
[2023-01-15T17:11:59Z DEBUG bollard::read] NewlineLogOutputDecoder: no header found, return LogOutput::Console
"2023-01-14T23:17:27.496421984-05:00 [lighttpd] 2023/01/14 23"
[2023-01-15T17:11:59Z DEBUG bollard::read] NewlineLogOutputDecoder: not enough data for read header
[2023-01-15T17:11:59Z DEBUG bollard::read] NewlineLogOutputDecoder: no header found, return LogOutput::Console
":17:27 2023-01-14 23:17:26: server.c.1513) server started (lighttpd/1.4.59)\r\n"
```

and using `curl -v --unix-socket /var/run/docker.sock "http://localhost/containers/0ba884c262b3/logs?stdout=true&timestamps=true"`, I get

```
*   Trying /var/run/docker.sock:0...
* Connected to localhost (/run/docker.sock) port 80 (#0)
> GET /containers/0ba884c262b3/logs?stdout=true&timestamps=true HTTP/1.1
> Host: localhost
> User-Agent: curl/7.74.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Api-Version: 1.41
< Docker-Experimental: false
< Ostype: linux
< Server: Docker/20.10.22 (linux)
< Date: Sun, 15 Jan 2023 17:29:02 GMT
< Transfer-Encoding: chunked
<
......
2023-01-14T23:17:26.551706337-05:00 [readsb] 2023/01/14 23:17:26 rtlsdr: tuner gain set to 38.6 dB
2023-01-14T23:17:27.496421984-05:00 [lighttpd] 2023/01/14 23:17:27 2023-01-14 23:17:26: server.c.1513) server started (lighttpd/1.4.59)
```

I am none the wiser

**Comment by fussybeaver** [comment]
Thanks for this...

It looks like the Docker logs on your platform are not emitting an 8 byte header as is normal, so Bollard's newline parser is emitting log lines in chunks as they are streamed. It should probably gracefully degrade to a newline parser.

I'll take a look if I can write a reproducible test case and fix.

**Comment by mrjackwills** [comment]
Thanks for the quick response and explanation, although it goes slightly over my head.
If you need me to test any code, on the real, badly behaving, hardware, let me know

**Comment by fussybeaver** [comment]
Could you check my branch with your platform to see whether the log behaviour is corrected? https://github.com/fussybeaver/bollard/pull/286

**Comment by mrjackwills** [comment]
Can confirm, that testing with the `ND-issue-285` branch, all 6000 lines of logs now all correctly start with the correct timestamp.
