### ISSUE TITLE
Creating a container

### ISSUE THREAD

**Issue by MoskalykA** [fussybeaver/bollard#288]
Hi,
I would like to know if there is a function to create a container from an image and specifying the version of this image?

**Comment by leon3s** [comment]
Yeah ofc

```rust
use bollard::container::{CreateContainerOptions, Config};

use std::default::Default;

let options = Some(CreateContainerOptions{
    name: "my-new-container",
});

let config = Config {
    image: Some("hello-world:some_version"),
    cmd: Some(vec!["/hello"]),
    ..Default::default()
};

docker.create_container(options, config);
```

**Comment by leon3s** [comment]
I suggest you to take a look at the [documentation](https://docs.rs/bollard/0.2.1/bollard/struct.Docker.html)

**Comment by MoskalykA** [comment]
> Yeah ofc
> 
> ```rust
> use bollard::container::{CreateContainerOptions, Config};
> 
> use std::default::Default;
> 
> let options = Some(CreateContainerOptions{
>     name: "my-new-container",
> });
> 
> let config = Config {
>     image: Some("hello-world:some_version"),
>     cmd: Some(vec!["/hello"]),
>     ..Default::default()
> };
> 
> docker.create_container(options, config);
> ```
> 
> I suggest you to take a look at the [documentation](https://docs.rs/bollard/0.2.1/bollard/struct.Docker.html)

Thanks 👍🏻
