### ISSUE TITLE
Feature request utoipa

### ISSUE THREAD

**Issue by leon3s** [fussybeaver/bollard#289]
Hey, since i use your model as input for my api, it could be nice to have them with the derive `ToSchema`

To have a compatibility with this crate: https://github.com/juhaku/utoipa

**Comment by fussybeaver** [comment]
I'm not sure we should add too many dependencies to the project.. If you just want to dump a schema, you could generate the models with the `ToSchema` derive locally.

Alternatively, we also follow this swagger schema, maybe it can be integrated into something else: https://raw.githubusercontent.com/moby/moby/a06bae909494b43daadc0ee60dbce79231616470/docs/api/v1.41.yaml

**Comment by leon3s** [comment]
If we add it as an optional feature what is the real problem ?
People that dont required it will see no changes.
Seems pretty dumb to me to recopy your datastructure to add one derive.
I'll have to add a From to convert it to your type, at this point, i can just rewrite the library i feel like.
And since there are generated from openapi model make sense to be able to regenerate their open api model back no ?

**Comment by fussybeaver** [comment]
I guess you don't need this for the buildkit protobuf files ?

**Comment by leon3s** [comment]
Sorry for coming off rude in the previous comment..
I dont need it for the buildkit only for models like ContainerConfig, ContainerInspect, ContainerSummary etc..
In my opinion it's a fair feature to have
