### ISSUE TITLE
attach_container example behaves weirdly

### ISSUE THREAD

**Issue by queil** [fussybeaver/bollard#291]
I am exploring your [attach_container.rs](https://github.com/fussybeaver/bollard/blob/master/examples/attach_container.rs) example and I expect it to show me a terminal command prompt so I can interact with the container. But I am not seeing anything I type until I press enter. Then it displays whatever I have typed and the result. Please take a look at the below gif. I am running it in WSL (Ubuntu 22.04, Docker Desktop 4.16.3 (96739))

P.S. [exec.rs](https://github.com/fussybeaver/bollard/blob/master/examples/exec_term.rs) example works fine on the other hand.

![attach_container](https://user-images.githubusercontent.com/4584075/220410155-bfa891a6-6760-4652-9893-7c21aa3f81b6.gif)

**Comment by fussybeaver** [comment]
I'm not really sure as I didn't work on that... but I guess we're not flushing the output until a newline is seen, which indicates that we should use something different than the newline stream decoder.

**Comment by queil** [comment]
Sadly, I am new to Rust so I won't be able to figure it out anytime soon. But using exec should be fine for my use case too. Interestingly, the stdin/stdout handling code seems to be pretty much the same in both examples.
