### ISSUE TITLE
IOError { err: Custom { kind: Other, error: "bytes remaining on stream" } } when pulling an image

### ISSUE THREAD

**Issue by jiridanek** [fussybeaver/bollard#292]
My code got an error from bollard, saying "bytes remaining on stream".

```rust
async fn docker_pull(docker: &Docker, image: &str) -> Vec<CreateImageInfo> {
    docker.create_image(Some(CreateImageOptions {
        from_image: image,
        ..Default::default()
    }), None, None).try_collect::<Vec<_>>().await.unwrap()
}
```

Here's the backtrace I got for it

```
thread 'testcontainers::test_h2spec::test_h2spec' panicked at 'called `Result::unwrap()` on an `Err` value: IOError { err: Custom { kind: Other, error: "bytes remaining on stream" } }', tests/testcontainers/test_h2spec.rs:223:51
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1791:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1113:23
   4: testcontainers::testcontainers::test_h2spec::docker_pull::{{closure}}
             at ./tests/testcontainers/test_h2spec.rs:220:5
```

What does this mean, and is this something I need to expect and handle? Is retry appropriate in this case?

I am using bollard v0.12.0, see other deps versions listed at https://github.com/skupperproject/skupper-router/pull/974/checks#step:6:48 if needed.

The error happened in a public CI job, and I only saw it happen this one time in a long while https://github.com/skupperproject/skupper-router/pull/974/checks#step:6:57

**Comment by fussybeaver** [comment]
That's a fairly old version, you might want to check with the latest Bollard version. We've had some problems parsing Docker's output on different architectures - are you running the GitHub action executor and docker server on a standard x86 linux architecture ?

Normally, this error indicates that Bollard's client closed the connection before the stream was done writing, perhaps the JSON wasn't handled sufficiently well...One would need to check output of the docker server - maybe by adding the `RUST_LOG=bollard=debug` environment variable and adding the `env_logger::try_init` statement before your test... although you suggest that this isn't a regular event... so maybe something else is going on.
