### ISSUE TITLE
'docker diff <running container id>'

### ISSUE THREAD

**Issue by sjmiller609** [fussybeaver/bollard#305]
Is there something like this in bollard? If not, any tips on adding the feature?

**Comment by fussybeaver** [comment]
This seems to be already implemented in the [container changes](https://docs.rs/bollard/latest/bollard/struct.Docker.html#method.container_changes) API as far as I can see in the [moby client code](https://github.com/moby/moby/blob/6eab4f55faf77bb0f253553d7d6fadb2ef6f4669/client/container_diff.go#L12-L23)

**Comment by sjmiller609** [comment]
Awesome! Thank you.
