### ISSUE TITLE
Make errors `std::error::Error`-compatible

### ISSUE THREAD

**Issue by mmstick** [fussybeaver/bollard#31]
The `failure::Error` type is not compatible with `std::error::Error`.

**Comment by fussybeaver** [comment]
I'm not 100% convinced that ditching `failure` is the correct approach. I know they've improved `std::error::Error`, but I'm wondering if they've completely superseded all of `failure`'s ergonomics.

I agree it would be useful to make errors compatible with `std::error::Error`. Maybe following the approach outlined in https://github.com/rust-lang-nursery/failure/blob/master/book/src/error-errorkind.md and https://www.reddit.com/r/rust/comments/8lt8k6/do_i_really_need_failureerrorchain/dzi7tnb/ would be a good approach.
