### ISSUE TITLE
Migrate `webpki` dependency to `rustls-webpki` to mitigate RUSTSEC-2023-0052

### ISSUE THREAD

**Issue by fuchsnj** [fussybeaver/bollard#327]
There is a security advisory for a CPU denial of service in the `webpki` crate, which is a dependency of `bollard`.
The `webpki` crate appears to be unmaintained. The latest version of `rustls-webpki` contains a fix for this.

Advisory: https://rustsec.org/advisories/RUSTSEC-2023-0052.html

**Comment by fussybeaver** [comment]
Yes, I can try to schedule a patch release in a couple of weeks when I'm back and have some time.

**Comment by dmartin** [comment]
Much appreciated, and thank you for all of your hard work on this library!
