### ISSUE TITLE
Events without options

### ISSUE THREAD

**Issue by yooouuri** [fussybeaver/bollard#337]
https://docs.docker.com/engine/reference/commandline/events/#limiting-filtering-and-formatting-the-output

The EventsOptions are mandatory, see the example states in the docs.

    /// use bollard::system::EventsOptions;
    /// use time::{Duration, OffsetDateTime};
    /// use std::collections::HashMap;
    ///
    /// # use bollard::Docker;
    /// # let docker = Docker::connect_with_http_defaults().unwrap();
    ///
    /// docker.events(Some(EventsOptions::<String> {
    ///     since: Some(OffsetDateTime::now_utc() - Duration::minutes(20)),
    ///     until: Some(OffsetDateTime::now_utc()),
    ///     filters: HashMap::new(),
    /// }));

But you can run the events command without `since`, `until` and `filters` options.

I need to listen for events, as long as my Application is running, without an until.

Sadly im a JS developer, having limited Rust experience, so I guess im not able to implement this myself 😞

**Comment by dmartin** [comment]
The `options` argument is an `Option`, so you could do something like:
```rust
docker.events::<String>(None);
```

**Comment by yooouuri** [comment]
> The `options` argument is an `Option`, so you could do something like:
> 
> ```rust
> 
> docker.events::<String>(None);
> 
> ```

Sorry didn't know that, I'm going to try it. Much thanks!
