### ISSUE TITLE
type_length_limit

### ISSUE THREAD

**Issue by bpmooch** [fussybeaver/bollard#359]
In https://github.com/fussybeaver/bollard/blob/master/examples/stats.rs, what is the purpose of `#![type_length_limit = "2097152"]`? I couldn't find anything in the docs.

**Comment by fussybeaver** [comment]
I'm unsure if it's still necessary since we now have impl traits, we can try and remove it, but in the past the type complexity was too high and this was necessary to get the project to build. https://doc.rust-lang.org/reference/attributes/limits.html#the-type_length_limit-attribute
