### ISSUE TITLE
Building an image using a local Dockerfile

### ISSUE THREAD

**Issue by bpmooch** [fussybeaver/bollard#367]
https://github.com/fussybeaver/bollard/blob/master/examples/build.rs

I am attempting to build an image using a local dockerfile:

```
        let dockerfile = test_dockerfile!("Dockerfile.minio");
        eprintln!("{dockerfile}");
        let build_image_options = BuildImageOptions {
            dockerfile,
            t: MINIO_IMAGE,
            nocache: true,
            rm: true,
            ..Default::default()
        };
        let mut image_build_stream = docker.build_image(build_image_options, None, None);
        while let Some(msg) = image_build_stream.try_next().await? {
            println!("Message: {msg:?}");
        }
```

I get an error from this code saying `DockerResponseServerError { status_code: 500, message: "Cannot locate spec
ified Dockerfile: /Users/mooch/p/sra/sherpa/api/resources/dockerfiles/Dockerfile.minio" }` but I am sure the file is in the correct place. I noticed in the example, a remote file is used. Is there something I'm missing about building a docker image from a local dockerfile?

**Comment by bpmooch** [comment]
I figured out the solution for this creating a tarball with the Dockerfile inside and using that as docker context for the build.

**Comment by fussybeaver** [comment]
Yeah, that's the correct way to upload a Dockerfile with the HTTP API... There is a more advanced mechanism using the new buildkit features and a GRPC interface, but I've yet to make an example / test case to show it works.

**Comment by gpollo** [comment]
I'm having the same problem. Just to be sure, if I want to do the equivalent to `docker build -f Dockerfile my-directory/` with `bollard`, I need to create a TAR archive with the following?
  * the `Dockerfile`, 
  * all files from `my-directory/`
    * minus files in the `my-directory/.dockerignore`,

Then, I can build using `build_image`? If I'm understanding this correctly, then perhaps it would be worth while to have helper functions for that in the future.

**Comment by Stargateur** [comment]
if the tar is mandatory why such option in `BuildImageOptions` ? and why the tar is optional `tar: Option<Bytes>`  ?

**Comment by fussybeaver** [comment]
I believe you can specify a remote dockerfile
