### ISSUE TITLE
How to specify multi-stage build target in build_image?

### ISSUE THREAD

**Issue by cylewitruk** [fussybeaver/bollard#391]
Hi!

Well I've been scouring the documentation/examples and searching the code for how I might do this and I just can't figure out how to pass the build target, i.e. the equivalent to `docker build --target runtime-stage .`. Am I missing something? :)
```
--target string                 Set the target build stage to build
```

**Comment by fussybeaver** [comment]
It looks like a field that's new and needs to be added to the `BuildImageOpts` struct. The query parameter models are not sourced from the openapi, so we need to maintain those manually..
