### ISSUE TITLE
Add a `Docker::connect_with_url()` method

### ISSUE THREAD

**Issue by xfbs** [fussybeaver/bollard#395]
Could we have a `connect_with_url()` method? I'm thinking to basically move use what you are doing in `connect_with_defaults`, and then call this method from `connect with defaults()`.

```rust
    pub fn connect_with_defaults() -> Result<Docker, Error> {
        let host = env::var("DOCKER_HOST").unwrap_or_else(|_| DEFAULT_DOCKER_HOST.to_string());
        Self::connect_with_url(host)
    }

    pub fn connect_with_url(host: &str) -> Result<Docker, Error> {
        match host {
            #[cfg(unix)]
            h if h.starts_with("unix://") => {
                Docker::connect_with_unix(&h, DEFAULT_TIMEOUT, API_DEFAULT_VERSION)
            }
            #[cfg(windows)]
            h if h.starts_with("npipe://") => {
                Docker::connect_with_named_pipe(&h, DEFAULT_TIMEOUT, API_DEFAULT_VERSION)
            }
            h if h.starts_with("tcp://") || h.starts_with("http://") => {
                #[cfg(feature = "ssl")]
                if env::var("DOCKER_TLS_VERIFY").is_ok() {
                    return Docker::connect_with_ssl_defaults();
                }
                Docker::connect_with_http_defaults()
            }
            #[cfg(feature = "ssl")]
            h if h.starts_with("https://") => Docker::connect_with_ssl_defaults(),
            _ => Err(UnsupportedURISchemeError {
                uri: host.to_string(),
            }),
        }
    }
```

**Comment by eddumelendez** [comment]
Hi, jumping here because I'm also interested in this issue. It would be nice to allow setting headers as well to set custom `User-Agent` from clients consuming the library. It would be even much better to accept a http request to make the client fully configurable.

**Comment by bpmooch** [comment]
@eddumelendez do you still care?

**Comment by DDtKey** [comment]
@bpmooch 
I'll put some context: we use `bollard` client in [Testcontainers for Rust ](https://github.com/testcontainers/testcontainers-rs/). And recently we completely switched to the `bollard` client, there is no issues with it and we don't depend on this issue. It was [customized](https://github.com/testcontainers/testcontainers-rs/blob/e354b7532b5d448ab37c9f95dab6c68c592cb62b/testcontainers/src/core/client/bollard_client.rs#L9-L41) and current interface is sufficient for this.

But the ability to customize the request still looks interesting, at least we would like to add the header (`User-Agent`).
However, IMO, this is question for a separate issue.

**Comment by fussybeaver** [comment]
@DDtKey @xfbs @bpmooch @eddumelendez There's an open PR tackling this issue, happy if any of you could have a quick look to check this will satisfy your needs https://github.com/fussybeaver/bollard/pull/459

**Comment by fussybeaver** [comment]
Closed due to a flexible implementation done in #459
