### ISSUE TITLE
Unclear error when docker is not running

### ISSUE THREAD

**Issue by cosmikwolf** [fussybeaver/bollard#399]
on Mac OS, I get the following error when I try and do:

`let docker =  Docker::connect_with_local_defaults().unwrap();`

```
called `Result::unwrap()` on an `Err` value: HyperLegacyError { err: Error { kind: Connect, source: Some(Os { code: 2, kind: NotFound, message: "No such file or directory" }) } }
```

In the errors file, all I could find is that the hyper legacy error should never happen.

Also I would expect that connect_with_local_defaults() would fail if the docker client is not running.

**Comment by fussybeaver** [comment]
Is this the same as #383 ?

**Comment by cosmikwolf** [comment]
ah yes, looks like a duplicate. closing. 

Thanks for your plugin! its rad :D
