### ISSUE TITLE
UpdateContainerOptions has i_ops and cp_us instead of iops and cpus

### ISSUE THREAD

**Issue by paul-hansen** [fussybeaver/bollard#408]
_Very_ minor thing, but in [UpdateContainerOptions](https://docs.rs/bollard/latest/bollard/container/struct.UpdateContainerOptions.html) i_ops and cp_us has an underscore in the wrong place compared to [HostConfig](https://docs.rs/bollard/0.16.1/bollard/models/struct.HostConfig.html) which has them as iops and cpus.

Seems to be the only on UpdateContainerOptions:
https://docs.rs/bollard/0.16.1?search=i_ops
https://docs.rs/bollard/0.16.1?search=cp_us

I'm hoping this is a super easy fix for someone as I'm not setup for Java dev to work on the codegen, but I might try it if no one picks it up.

Thanks for this library, it's been great!

**Comment by fussybeaver** [comment]
Thanks, the input parameters (so all the `*Options` structs) are not governed by the swagger API documentation, so we can just edit those directly in `src/container.rs`.

**Comment by paul-hansen** [comment]
Oh nice! Knowing that, I tried to do this in https://github.com/fussybeaver/bollard/pull/410 

I went ahead and updated a couple other things on that struct too after reviewing docker's API. I think they all make sense but lmk if any of that shouldn't have been done.
