### ISSUE TITLE
Both ring and aws-lc-rs provider are enabled

### ISSUE THREAD

**Issue by stormshield-gt** [fussybeaver/bollard#440]
Even if the ring feature is enabled, default-feature of `rustls` are still enabled, so `aws-lc-rs` provider is also a dependency.

```sh
$ cargo tree --workspace --target all --all-features -i aws-lc-rs
aws-lc-rs v1.8.1
├── rustls v0.23.12
│   ├── bollard v0.17.0 (/tmp/bollard)
│   ├── hyper-rustls v0.27.2
│   │   └── bollard v0.17.0 (/tmp/bollard)
│   ├── tokio-rustls v0.26.0
│   │   └── hyper-rustls v0.27.2 (*)
│   └── ureq v2.10.0
│       ├── bollard-buildkit-proto v0.4.0 (/tmp/bollard/codegen/proto)
│       │   ├── bollard v0.17.0 (/tmp/bollard)
│       │   └── bollard-stubs v1.45.0-rc.26.0.1 (/tmp/bollard/codegen/swagger)
│       └── bollard-buildkit-proto v0.4.0
│           └── bollard-stubs v1.45.0-rc.26.0.1
│               └── bollard v0.17.0 (/tmp/bollard)
└── rustls-webpki v0.102.6
    └── rustls v0.23.12 (*)
```

```sh
$ cargo tree --workspace --target all --all-features -i ring
ring v0.17.8
├── rustls v0.23.12
│   ├── bollard v0.17.0 (/tmp/bollard)
│   ├── hyper-rustls v0.27.2
│   │   └── bollard v0.17.0 (/tmp/bollard)
│   ├── tokio-rustls v0.26.0
│   │   └── hyper-rustls v0.27.2 (*)
│   └── ureq v2.10.0
│       ├── bollard-buildkit-proto v0.4.0 (/tmp/bollard/codegen/proto)
│       │   ├── bollard v0.17.0 (/tmp/bollard)
│       │   └── bollard-stubs v1.45.0-rc.26.0.1 (/tmp/bollard/codegen/swagger)
│       └── bollard-buildkit-proto v0.4.0
│           └── bollard-stubs v1.45.0-rc.26.0.1
│               └── bollard v0.17.0 (/tmp/bollard)
└── rustls-webpki v0.102.6
    └── rustls v0.23.12 (*)
```
I'm not sure if this the wanted behavior, correct me if I'm wrong.

As bollard is meant to be used as a library, the current [rustls recommendation ](https://docs.rs/rustls/latest/rustls/crypto/struct.CryptoProvider.html#using-the-per-process-default-cryptoprovider) is trying to fetch the provider from the process and not installing it. To make a comparison,  libraris are not supposed to install the `tracing subscriber`.

But we can still provide a feature (`ring` for instance), that can be default, that provide installations. That's what the rest of the ecosystem tends to do, see [tokio-rustls](https://docs.rs/crate/tokio-rustls/latest/features) or [hyper-rustls](https://docs.rs/crate/hyper-rustls/latest/features).

**Comment by fussybeaver** [comment]
Happy to accept a PR for this
