### ISSUE TITLE
Docker::connect_with_transport

### ISSUE THREAD

**Issue by izissise** [fussybeaver/bollard#458]
Hello,

I'd like to connect to a docker daemon with tls certificate, but the certificate are never stored on the filesystem client side.
[connect_with_ssl](https://docs.rs/bollard/latest/bollard/struct.Docker.html#method.connect_with_ssl) only take `Path` for keys. 

Would it be possible to have a constructor that take directly a `Transport` so a user can set it up themselve.
An alternative would be to able to pass a `rustls::ClientConfig`.

I'm willing to contribute this, what do you think?

Thanks,
Hugues

Edit: I think this could also make it possible to tunnel through ssh https://github.com/fussybeaver/bollard/issues/244

**Comment by fussybeaver** [comment]
Yes, I'm definitely interested. There was some conversation recently around request customisation ( https://github.com/fussybeaver/bollard/issues/395#issuecomment-2245054968  and https://github.com/fussybeaver/bollard/issues/436 ), so it would be interesting to see if this implementation can be used as a template to solve that problem too.

**Comment by fussybeaver** [comment]
@izissise can we close this, due to #459 ?
