### ISSUE TITLE
Migrate to Non-Fork Repository

### ISSUE THREAD

**Issue by zicklag** [fussybeaver/bollard#48]
To increase discoverability on GitHub I think it would be good to migrate the repository to a standalone repository so that it will pop up in GitHub searches. I almost didn't find it because I found the repository that it was forked from instead.

You have to contact GitHub support to have them migrate the repo: https://help.github.com/en/articles/why-are-my-contributions-not-showing-up-on-my-profile#commit-was-made-in-a-fork.

**Comment by fussybeaver** [comment]
Thanks, I opened a github support ticket, and it was done pretty promptly.

**Comment by zicklag** [comment]
Cool. :slightly_smiling_face: :tada:
