### ISSUE TITLE
No support for importing images from tarball.

### ISSUE THREAD

**Issue by Bunogi** [fussybeaver/bollard#54]
The documentation mentions this being unsupported, but it would be great to have a function for using the `/images/load` endpoint easily. Currently, my workaround is to create an image from a filesystem tarball instead, which has a number of drawbacks.

**Comment by fussybeaver** [comment]
We don't have that API yet, but it doesn't look too complicated to implement. I may be missing something here, but the Docker API documentation mentions that the `/images/load` API requires a tarball as the body to the payload, so at best you'd still need to write the tarball (potentially in memory) and offload it into this library.
