### ISSUE TITLE
Are you interested in replacing openssl with rustls?

### ISSUE THREAD

**Issue by emk** [fussybeaver/bollard#57]
Hello! I'm the maintainer of `boondock`, a barely-maintained Docker client for Rust. I'm hoping to migrate away from it at some point, and `bollard` is on my shortlist.

There's one piece of potentially interesting code in `boondock`: A `hyperlocal` + `rustls` connection routine, which you can find [here](https://github.com/faradayio/boondock/blob/master/src/connector.rs). The completely removes the dependency on OpenSSL, and it makes it easy to use the same code to talk to either `unix://` sockets or `https://` endpoints. It implements Docker-compatible certificate and key management.

If you'd be interested in switching to this at some point, I'd be happy to answer questions and maybe help with the integration.

**Comment by fussybeaver** [comment]
Oh hi... Sounds very interesting, I'd be happy to see support for this, feel free to work on a PR if you have the time to do so. Also, nice to see this improvement in `boondock`!

We have both an SSL hyper connector and a TLS connector (which uses `hyper-tls`). A good portion of that code would no longer be needed.
