### ISSUE TITLE
Handle health check results with negative exit code values

### ISSUE THREAD

**Issue by simonsparks** [fussybeaver/bollard#68]
In some cases, the `HealthcheckResult`s returned from a Docker inspection call may include negative `ExitCode` values which currently don't deserialize to the `u16` type defined in `container.rs`.

An example case was found when launching `postgres:alpine` in Docker (API version 1.40) with a healthcheck command of `CMD /bin/su - postgres -c /usr/local/bin/pg_isready`. Until the result of this command is successful, the exit code received is `-1`, causing a panic:
```
Failed to deserialize JSON: invalid value: integer `-1`, expected u16 at ...
```

If the LogStateHealth struct is modified to use an `i16` exit_code type, the inspection is successful:
```
/// Log of the health of a running container.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
#[allow(missing_docs)]
pub struct LogStateHealth {
    pub start: DateTime<Utc>,
    pub end: DateTime<Utc>,
    pub exit_code: i16,
    pub output: String,
}
```

According to the [API spec](https://docs.docker.com/engine/api/v1.40/) there is a limited set of known values and a catchall "other values" in the ExitCode description:
```
ExitCode:
        description: |
          ExitCode meanings:

          - `0` healthy
          - `1` unhealthy
          - `2` reserved (considered unhealthy)
          - other values: error running probe
        type: "integer"
        example: 0
```
A `-1` value has been found to be one of those other values but I don't know whether an `i16` type would restrict bollard from catching all possible values. In theory it may only need to cover the 8 bit range if following unix-like conventions. An `i8` works for this issue but an `i16` would give a more tollerant range.

**Comment by fussybeaver** [comment]
Good catch. I'm looking at generating these stubs through the swagger API in future, so hopefully we won't have so many issues like these going forwards..

**Comment by simonsparks** [comment]
No problem.
Sounds like a good idea; I need to look into swagger codegen for rust as well.
