### ISSUE TITLE
container `Config<T>` is not Deserialize after upgrade to v0.6

### ISSUE THREAD

**Issue by valbendan** [fussybeaver/bollard#75]
In version v0.5, the `Config<T>` derived serde `Deserialize`, after upgrade to v0.6  [Config< T > ](https://github.com/fussybeaver/bollard/blob/8ba2595fff5f69c1aa72ef501420230363b74a50/src/container.rs#L162) only derived `Serialize`. 

Other struct like: `NetworkingConfig`,  `HealthConfig`  etc .. seems are all derived `Deserialize`,
If it is possible add `Deserialize` back for `Config<T>` ?

 It's a breaking change after all. (At least break my code 😄  )

**Comment by fussybeaver** [comment]
You need to use `models::ContainerConfig` https://docs.rs/bollard/0.6.0/bollard/models/struct.ContainerConfig.html
for deserialization. Does that solve your problem?

**Comment by valbendan** [comment]
It seems that `Docker.create_container` method accept `Config< T >` instead of `models::ContainerConfig`, I have not found there is a trivial way convert  `ContainerConfig` to `Config< T >`.

My main use case is load docker config from file (eg: json),  create and  run the container.

PS: It seems `ContainerConfig` and  `Config< T >` have very similar fields ?

**Comment by fussybeaver** [comment]
In the Docker/Swagger API, they are treated differently - it wasn't possible to combine the two types like I did in the previous versions.. maybe as a solution we can provide an `into` trait to convert between the two.

**Comment by valbendan** [comment]
It will be awesome.
