### ISSUE TITLE
Signature of Docker::start_exec() contradicts its usage

### ISSUE THREAD

**Issue by rami3l** [fussybeaver/bollard#86]
## Problem

The signature of the `bollard::Docker::start_exec()` function is misleading: `container_name` is actually the `id` field of a created `Docker exec` instance.

## Details

While using the `Docker exec` API, I want to use the `start_exec` function.

I noticed that the signature of this function is as follows:

https://github.com/fussybeaver/bollard/blob/c720ee74c0172a0aa88c9780fdbbea9e71221090/src/exec.rs#L165-L167
https://github.com/fussybeaver/bollard/blob/c720ee74c0172a0aa88c9780fdbbea9e71221090/src/exec.rs#L183-L187

I tried to pass a predefined `container_name` to this function, but I got a `404` error.

Fortunately, I have found the real usage of this function in your tests:

https://github.com/fussybeaver/bollard/blob/c720ee74c0172a0aa88c9780fdbbea9e71221090/tests/exec_test.rs#L18-L19
https://github.com/fussybeaver/bollard/blob/c720ee74c0172a0aa88c9780fdbbea9e71221090/tests/exec_test.rs#L38-L39

**Comment by fussybeaver** [comment]
OK thanks, I guess we just need to update the documentation and argument name..

**Comment by rami3l** [comment]
@fussybeaver Additionally, I tested the `inspect_exec` function, and I believe there is a similar problem.
