### ISSUE TITLE
Don't prefix public struct members with underscores

### ISSUE THREAD

**Issue by mdonoughe** [fussybeaver/bollard#87]
Identifiers beginning with underscores are reserved for values that are not used. Bollard [uses `_type`](https://docs.rs/bollard/0.7.1/bollard/service/struct.SystemEventsResponse.html), presumably to avoid clashing with the reserved keyword `type`. This triggers the Clippy lint [used_underscore_binding](https://rust-lang.github.io/rust-clippy/master/index.html#used_underscore_binding) in consuming code.

Unfortunately, changing the name of this field is obviously a breaking change.

**Comment by fussybeaver** [comment]
I think it would be useful to go through all the clippy recommendations in a PR..
